# Generated by Django 4.1.7 on 2023-03-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='impressions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(max_length=250, verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='posts', verbose_name='image'),
        ),
    ]
