# Generated by Django 4.1.7 on 2023-03-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_impressions_alter_post_excerpt_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='impressions',
        ),
    ]
